# Generated by Django 5.1.6 on 2025-05-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulo', models.CharField(max_length=100)),
                ('significado', models.CharField(max_length=200)),
                ('exemplo', models.CharField(max_length=200)),
                ('frequencia', models.CharField(choices=[('alta', 'alta'), ('media', 'media'), ('baixa', 'baixa')], default='media', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
